source $HOME/.zprezto/runcoms/zshrc

export LIMA_INSTANCE=docker
compctl -g '~/.teamocil/*(:t:r)' teamocil
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

